### ISSUE TITLE
attempt to install on rapi4/ubuntu 20.04 fail - old references to BroString.h

### ISSUE THREAD

**Issue by jsutch** [esnet/zeek-exporter#8]
Attempting to do a zkg install on raspi4/ubuntu 20.04 - apparently trying to operate on old BroString references. 

~# uname -a
Linux snout 5.4.0-1044-raspi #48-Ubuntu SMP PREEMPT Thu Sep 9 15:24:01 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

zeek version 4.2.0-dev.94

Error.
=== STDERR ===
make: [Makefile:12: build-it] Error 1 (ignored)
/root/.zkg/testing/zeek-exporter/clones/zeek-exporter/src/Plugin.cc:8:10: fatal error: BroString.h: No such file or directory
    8 | #include <BroString.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/ESnet-Zeek_Exporter.linux-aarch64.dir/build.make:82: CMakeFiles/ESnet-Zeek_Exporter.linux-aarch64.dir/src/Plugin.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:404: CMakeFiles/ESnet-Zeek_Exporter.linux-aarch64.dir/all] Error 2
make[1]: *** [Makefile:152: all] Error 2
make: *** [Makefile:13: build-it] Error 2
=== STDOUT ===
Build Directory        : build

**Comment by dopheide-esnet** [comment]
Fixed this awhile back, forgot to close the issue.
